FITlosophiMVC/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using FITlosophiBLL;
using FITlosophiData.Models;
using FITlosophiMVC.Models;

namespace FITlosophiMVC.Controllers
{
    public class CMSController : Controller
    {
        // GET: CMS
        public ActionResult Index()
        {
            return View();
        }

        #region Post

        [Authorize]
        public ActionResult ManagePosts()
        {
            if (User.IsInRole("Admin"))
            {
                return View();

            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult AddPost()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult PostPost(Post post)
        {
            var create = new FITlosophiOperations();

            create.AddPost(post);

            if (User.IsInRole("Admin"))
            {
                return View("ManagePosts");
            }


            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles="Admin")]
        public ActionResult EditPost(int id)
        {
            var read = new FITlosophiOperations();

            var postToEdit = read.GetPostByID(id);

            return View(postToEdit);
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        public ActionResult EditPost(Post post)
        {
            var update = new FITlosophiOperations();

            update.EditPost(post);

            return View("ManagePosts");
        }

        #endregion

        #region Page


        [Authorize]
        public ActionResult ManagePages()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult AddPage()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult PostPage(StaticPage page)
        {
            var create = new FITlosophiOperations();

            create.AddStaticPage(page);

            if (User.IsInRole("Admin"))
            {
                return View("ManagePages");
            }


            return RedirectToAction("Index", "Home");

        }

        [Authorize(Roles="Admin")]
        public ActionResult EditPage(int id)
        {
            var read = new FITlosophiOperations();

            var pageToEdit = read.GetPageByID(id);

            return View(pageToEdit);
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        public ActionResult EditPage(StaticPage page)
        {
            var update = new FITlosophiOperations();

            update.EditPage(page);

            return View("ManagePages");
        }

        #endregion



    }
}

FITlosophiMVC/Views/Shared/_AddImageModal.cshtml
<div class="modal fade" id="addImageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Uploade Image</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h5 id="ModalMessage"></h5>
                            <input type="hidden" id="imageURL"/>
                            <div>
                                <form class="upload_form"></form>
                                <div class="progress-bar" >
                                    <div class="progress"></div>
                                </div>
                                <div class="form_line">
                                    <div class="form_controls">
                                        <div class="preview"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-success" id="btnConfirm">Submit</button>
            </div>
        </div>
    </div>
</div>


    

FITlosophiMVC/Views/Shared/_ImageGallery.cshtml
<aside id="imageWidget" class="col-md-3" style="margin-top: 40px; overflow-x: hidden; overflow-y: scroll; height: 600px;">
    <!-- Least Gallery -->
    <section id="least">

        <!-- Least Gallery: Fullscreen Preview -->
        <div class="least-preview"></div>

        <!-- Least Gallery: Thumbnails -->
        <ul class="least-gallery" id="blogImageGallery">
            <!-- 1th thumbnail -->
        </ul>
    </section>
</aside>

FITlosophiMVC/Views/Shared/_ImageURLGenerator.cshtml
<div class="modal fade" id="imageGeneratorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Upload Image</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h5 id="ModalMessage"></h5>
                            <input id="imageURL" type="text" class="form-control input-lg" placeholder="Image URL"/>
                            <br/>
                            <div>
                                <form class="upload_form"></form>
                                <div class="progress-bar">
                                    <div class="progress"></div>
                                </div>
                                <div class="form_line">
                                    <div class="form_controls">
                                        <div class="preview"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

FITlosophiMVC/Views/Shared/_Layout.cshtml
@using System
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <title>@ViewBag.Title - FITlosophi</title>

    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="~/Content/node_modules/font-awesome/css/font-awesome.min.css">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="~/Content/css/styles-bluegreen.css" id="theme-styles">
    <link rel="stylesheet" href="~/Content/less/layout.less"/>
    <link href="~/Content/css/blogSummary.css" rel="stylesheet" />

    <!--[if lt IE 9]>
        <script src="~/Content/node_modules/respond.js/dest/respond.min.js"></script>
    <![endif]-->

    <!--Tagit General CSS-->
    <link href="~/Content/css/tagit/jquery.tagit.css" rel="stylesheet" type="text/css">

    <!--Tagit Theme-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/tagit/tagit.ui-zendesk.css">

    <!--TinyMCE JS files-->
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>

    <!-- JQuery UI for Search Bar-->
    <link href="~/Content/css/jquery-ui.css" rel="stylesheet"/>

    <!-- least.js 2 CSS file -->
    <link href="~/Scripts/leastjs/css/least.min.css" rel="stylesheet"/>
  

</head>

<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="/Home/index" id="logo">
                    <img src="~/Content/img/logo.png" height="100" alt="Fitlosophi Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".tales-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right tales-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                            <li><a href="/Home/Index" >Blog</a></li>
                            <li><a href="/Home/About" >About</a></li>
                            <li class="dropdown" id="PagesDropdown">
                                <a class="dropdown-toggle"
                                   data-toggle="dropdown"
                                   href="#">
                                    Pages
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" id="StaticPageMenu">
                                </ul>
                            </li>
                            <li>
                            @if (Request.IsAuthenticated)
                            {
                                <li class="dropdown">
                                    <a class="dropdown-toggle"
                                        data-toggle="dropdown"
                                        href="#">
                                        Admin
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                                        {
                                            <li>@Html.ActionLink("Add Post", "AddPost", "CMS")</li>
                                        }
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("Manage Posts", "ManagePosts", "CMS")</li>
                                        }
                                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                                        {
                                            <li>@Html.ActionLink("Add Page", "AddPage", "CMS")</li>
                                        }
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("Manage Pages", "ManagePages", "CMS")</li>
                                            <li>@Html.ActionLink("Register User", "Register", "Account")</li>
                                        }
                                    </ul>
                                </li>
                            }

                                @Html.Partial("_LoginPartial")

                        </ul>
                    </div>
                </nav>

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="tales-breadcrumb">
                    @if (Request.IsAuthenticated)
                    {
                        <text>Hi @(char.ToUpper(User.Identity.Name.Substring(0,User.Identity.Name.IndexOf("@"))[0]) + User.Identity.Name.Substring(1,User.Identity.Name.IndexOf("@")-1))!</text>
                    }
                </div>
                <div class="tales-searchbox">
                    <form action="/Home/BlogByTagID" id="tagformid" method="get" accept-charset="utf-8">

                        <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                        <input type="hidden" name="TagID" id="TagID" value="0"/>
                        <input type="hidden" name="Page" id="Page" value="1"/>
                        <input class="searchfield ui-autocomplete-input" id="searchbox" type="text" placeholder="Hashtag Search">
                    </form>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="widewrapper main">
                <div class="container">
                    @RenderBody()
                </div>
            </div>
        </div>
</header>
    <footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-star"></i> Writer's Mantra
                        </h3>
                        <ul class="tales-list">
                            <li>Living healthy is about eating healthy.</li>
                            <li>Being fit is a lifestyle not a short term goal.</li>
                            <li>Share ideas, tips, and recipes to promote wellness. </li>
                            <li>Healthy is happy.</li>
                        </ul>
                    </div>
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i>Contact Us
                        </h3>
                        <span>We love to hear from my readers. Thoughts, feedback, critique - all welcome! Drop me a line:</span>

                        <span class="email">
                            <a href="#">feedback@FITlosophi.com</a>
                        </span>
                    </div>
                    <div class="col-md-4 footer-widget">
                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <h3>
                                <i class="fa fa-cog"></i>Statistics
                            </h3>
                            <span>Even we sometimes loose track of how many articles we actually have here.</span>
                            <div class="stats">
                                <div class="line">
                                    <span class="counter">27</span>
                                    <span class="caption">Articles</span>
                                </div>
                                <div class="line">
                                    <span class="counter">2</span>
                                    <span class="caption">Authors</span>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
            <div class="container">
                <p>&copy; @DateTime.Now.Year - FITlosophi</p>
            </div>
        </div>
    </footer>



<!--JQuery JS files-->
<script src="~/Scripts/jquery-2.1.4.min.js"></script>

<!--Bootstrap JS files-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!--JQueryUI files-->
<script src="~/Scripts/jquery-ui.min.js"></script>">

<!--Dynamic Pages Menu -->
<script src="~/Scripts/app/loadStaticPages.js"></script>

<!--Hashtag Search Autocomplete -->
<script src="~/Scripts/app/hashTagSearch.js"></script>

<!--JQuery Validate-->
<script src="~/Scripts/jquery.validate.min.js"></script>

@RenderSection("scripts", required: false)

</body>
</html>

FITlosophiMVC/Views/Shared/_ManagePageModal.cshtml
<div class="modal fade" id="managePageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body">
                <h5 id="ModalTitle"></h5>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h5 id="ModalMessage"></h5>

                            <input type="hidden" id="PageID" />

                        </div>                    
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-tales-one" id="btnConfirm">Confirm</button>
            </div>
        </div>
    </div>
</div>

FITlosophiMVC/Views/Shared/_ManagePostsModal.cshtml
<div class="modal fade" id="managePostsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="modal-body">
                <h5 id="ModalTitle"></h5>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h5 id="ModalMessage"></h5>
                            <input type="hidden" id="PostID"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-tales-one" id="btnConfirm">Confirm</button>
            </div>
        </div>
    </div>
</div>

FITlosophiMVC/Views/Shared/_PublishModal.cshtml
<div class="modal fade" id="PublishModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="PublishModalTitle">Publish</h4>
            </div>
            <div class="modal-body">
                <h5 id="PublishModalBodyTitle"></h5>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h5 id="PuBlishModalMessage">
                                Publish wish auto-scheduling?
                                <br/>
                                <input type="radio" class="HasSchedule" value="1"/>Yes
                                <br/>
                                <input type="radio" class="HasSchedule" value="0" checked/>No
                            </h5>
                            <div id="PostScheduler" style="display: none">
                                <label for="FromDate">From</label>
                                <input type="text" id="FromDate"/>
                                <label for="ToDate">To</label>
                                <input type="text" id="ToDate"/>
                            </div>
                            <input type="hidden" id="PublishModalPostID" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-tales-one" id="PublishConfirm">Publish</button>
            </div>
        </div>
    </div>
</div>